@startuml UML Simplificado


entity Voluntario
entity Organizador
entity Actividad
entity InstanciaActividad
entity Inscripcion
entity Comentario
entity Badge
entity Categoria
entity Notificacion

Voluntario ||--o{ Inscripcion : "realiza"
InstanciaActividad ||--o{ Inscripcion : "tiene"

Actividad ||--o{ InstanciaActividad : "genera"
Organizador ||--o{ Actividad : "crea"

Voluntario ||--o{ Comentario : "escribe"
Comentario }o--|| Actividad : "sobre"
Comentario }o--|| Organizador : "sobre"

Voluntario ||--o{ Badge : "obtiene"

Actividad ||--o{ Categoria : "pertenece"
Organizador ||--o{ Categoria : "enfocado"
Voluntario ||--o{ Categoria : "interesado"

Voluntario ||--o{ Notificacion : "recibe"

@enduml
