@startuml UML Detallado


entity "Voluntario" as Voluntario {
  *id_voluntario : int
  --
  username : string
  email : string
  password : string
  name : string
  lastname : string
  age : int
  genre : string
  fecha_registro : datetime
}

entity "Organizador" as Organizador {
  *id_centro : int
  --
  username : string
  email : string
  contactEmail : string
  password : string
  name : string
  telephone : string
  social : string
  location : string
  lat : decimal
  lng : decimal
}

entity "Actividad" as Actividad {
  *id_actividad : int
  --
  owner : Organizador
  title : string
  description : text
  date : datetime
  status : string
  location : string
  locationCoordinates : string
  instances : InstanciaActividad
}

entity "InstanciaActividad" as Instancia {
  *id_instancia : int
  --
  owner : Organizador
  activity : Actividad
  date : datetime
  duration : int
  status : string
  inscriptionsAmount : int
  quota : int
}

entity "Inscripcion" as Inscripcion {
  *id_inscripcion : int
  --
  volunteer : Voluntario
  accepted : boolean
  date : datetime
  assisted : boolean
}

entity "Comentario" as Comentario {
  *id_comentario : int
  --
  texto : text
  rating : int
  anonimo : boolean
  fecha : datetime
  tipo_objetivo : string  // "Actividad" o "Organizador"
}

entity "Badge" as Badge {
  *id_badge : int
  --
  titulo : string
  descripcion : text
  condicion : string
  imagen : string
  fecha_obtencion : datetime
}

entity "Categoria" as Categoria {
  *id_categoria : int
  --
  nombre : string
  descripcion : text
}

entity "Notificacion" as Notificacion {
  *id_notificacion : int
  --
  tipo : string
  mensaje : text
  fecha_envio : datetime
  leida : boolean
}

' =========================
' RELACIONES
' =========================
Voluntario ||--o{ Inscripcion : "realiza"
Instancia ||--o{ Inscripcion : "tiene"

Actividad ||--o{ Instancia : "genera"
Organizador ||--o{ Actividad : "crea"

Voluntario ||--o{ Comentario : "escribe"
Comentario }o--|| Instancia : "sobre"
Comentario }o--|| Organizador : "sobre"

Voluntario ||--o{ Badge : "obtiene"

Actividad ||--o{ Categoria : "pertenece"
Organizador ||--o{ Categoria : "enfocado"
Voluntario ||--o{ Categoria : "interesado"

Voluntario ||--o{ Notificacion : "recibe"

@enduml
